name: Deploy Docs

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies for pycairo
        run: sudo apt-get update && sudo apt-get install -y libcairo2-dev      

      - name: Install dependencies
        run: |

          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt  # if needed

      - name: Build docs
        run: |
          cd docs
          make clean html  # or sphinx-build -b html source build/html
          cd ..

      - name: Deploy to Repo B

        run: |
           git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/plixlab/plixlab.github.io.git repo-b

           rm -rf repo-b/*
           cp -r docs/build/html/* repo-b/

           cd repo-b
           git config user.name "github-actions"
           git config user.email "github-actions@github.com"
           git add .

           if ! git diff --cached --quiet; then
            git commit -m "Update docs from plixlab.io"
            git push
           else
            echo "No changes to commit"
